### ISSUE TITLE
Tab key navigation

### ISSUE THREAD

**Issue by edvasqueza** [st3ph/jquery.easyWizard#6]
Hi, there is a problem in the layout when you navigate forms in the wizard with the tab key. It happens even in the demo:
![captura](https://f.cloud.github.com/assets/855077/2453214/633d32b8-aedb-11e3-980c-7281a0e88cc8.PNG)

**Comment by vsagthi** [comment]
I am having the same issue in my app and your demo helped me but i want it for listitems .
please can you help me?
